"""Recreate migrations

Revision ID: 37f4989fd6b0
Revises: 3efae290696f
Create Date: 2024-08-19 21:22:50.310208

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "37f4989fd6b0"
down_revision = "3efae290696f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
